Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace waSEMANA077.Models
{
    public class Categoria
    {
       [Required] public int idCategoria {get; set;}

        [Required] public string NombreCategoria { get;set;}

        [Required]   public string Descripcion { get; set;}  

        public Categoria() { }
    }
}

Models/DaoCategoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;


namespace waSEMANA077.Models
{
    public class DaoCategoria
    {
        static string cadena = ConfigurationManager.ConnectionStrings["cn"].ConnectionString;
        private SqlConnection cn = new SqlConnection(cadena);

        public Boolean Insertar(Categoria obj)
        {
            SqlCommand cmd = new SqlCommand("Compras.usp_insertar_categorias", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@idcat", obj.idCategoria);
            cmd.Parameters.AddWithValue("@nomcat", obj.NombreCategoria);
            cmd.Parameters.AddWithValue("@descat", obj.Descripcion);
            try
            {
                cn.Open();
                cmd.ExecuteNonQuery();
                return true;


            } catch (SqlException ex)
            {
                Console.WriteLine(ex.ToString());
                return false;
            }
            finally
            {
                cn.Close();
                cmd.Dispose();
            }

        }

    }
}

Models/DaoObrero.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace waSEMANA077.Models
{
    public class DaoObrero
    {
        static string cadena = ConfigurationManager.ConnectionStrings["cn"].ConnectionString;
        private SqlConnection cn = new SqlConnection(cadena);

        public Boolean Insertar(Obrero obj)
        {
            SqlCommand cmd = new SqlCommand("sp_insertar_obrero", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@id_obrero", obj.id_obrero);
            cmd.Parameters.AddWithValue("@nombre", obj.nombre);
            cmd.Parameters.AddWithValue("@apellido", obj.apellido);
            cmd.Parameters.AddWithValue("@dni", obj.dni);
            cmd.Parameters.AddWithValue("@genero", obj.genero);
            cmd.Parameters.AddWithValue("@sueldo", obj.sueldo);
            cmd.Parameters.AddWithValue("@fecha_naci", obj.fecha_naci);
            try
            {
                cn.Open();
                cmd.ExecuteNonQuery();
                return true;
            }
            catch (SqlException ex)
            {
                Console.WriteLine(ex.ToString());
                return false;
            }
            finally
            {
                cn.Close();
                cmd.Dispose();
            }

        }
    }
}

Models/Obrero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace waSEMANA077.Models
{
    public class Obrero
    {
        [DisplayName("CODIGO")][Required] public int id_obrero {  get; set; }
        [DisplayName("NOMBRE")][Required] public string nombre { get; set; }
        [DisplayName("APELLIDOS")][Required] public string apellido { get; set; }
        [DisplayName("DNI")][Required] public int dni { get; set; }
        [DisplayName("GENERO")][Required] public string genero { get; set; }
        [DisplayName("SUELDO")][Required] public decimal sueldo { get; set; }
        [DisplayName("FECHA DE NACIMIENTO")][Required] public DateTime fecha_naci {get; set; }

        
        public Obrero()
        {
            fecha_naci = new DateTime(1753, 1, 1);
        }

    }
}

Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using waSEMANA077.Models;

namespace waSEMANA077.Controllers
{
    public class CategoriaController : Controller
    {
        // GET: Categoria
        public ActionResult Nuevo(Categoria obj)
        {
            ViewBag.IdCategoria = obj.idCategoria;
            ViewBag.NombreCategoria = obj.NombreCategoria;
            ViewBag.Descripcion = obj.Descripcion;
            DaoCategoria dao = new DaoCategoria();
            if (dao.Insertar(obj))
            {
                ViewBag.mensaje = "Categoria Insertada Con Exitos";
            }
            else
            {
                ViewBag.mensaje = "Error al insertar la categoria";
            }
            return View();
        }

        public ActionResult Create(Categoria obj)
        {
            ViewBag.IdCategoria = obj.idCategoria;
            ViewBag.NombreCategoria = obj.NombreCategoria;
            ViewBag.Descripcion = obj.Descripcion;
            DaoCategoria dao = new DaoCategoria();
            if (dao.Insertar(obj))
                ViewBag.mensaje = "Categoria Insertada Con Exitos";
            
            return View(obj);
        }
    }
}

Controllers/ObreroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using waSEMANA077.Models;

namespace waSEMANA077.Controllers
{
    public class ObreroController : Controller
    {
        // GET: Obrero
        public ActionResult Nuevo(Obrero obj)
        {
            ViewBag.id=obj.id_obrero;
            ViewBag.nombre=obj.nombre;
            ViewBag.apellido=obj.apellido;
            ViewBag.dni=obj.dni;
            ViewBag.genero=obj.genero;
            ViewBag.sueldo=obj.sueldo;
            ViewBag.fecha_naci=obj.fecha_naci;
            DaoObrero dao = new DaoObrero();
            if(dao.Insertar(obj))
            {
                ViewBag.mensaje = "Obrero agregado exitosamente";

            }
            else
            {
                ViewBag.mensaje = "Error al registrar Obrero";
            }
                    
            return View();
        }
    }
}

Views/Categoria/Create.cshtml
@model waSEMANA077.Models.Categoria


<h2>Crear Categoria</h2>



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div style="" class="form-horizontal">
        <h4>Categoria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idCategoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idCategoria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idCategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreCategoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreCategoria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreCategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <p>
        <strong>@ViewBag.mensaje</strong>
    </p>
</div>

Views/Categoria/Nuevo.cshtml
@{
    ViewBag.Title = "Nuevo";
}

<h2>Nueva Categoria</h2>
@using (Html.BeginForm("Nuevo", "Categoria", FormMethod.Post))
{
    <p>
        @Html.Label("ID")<br />
        @Html.TextBox("idCategoria")
    </p>
    <p>
        @Html.Label("Nombre")<br />
        @Html.TextBox("NombreCategoria")
    </p>
    <p>
        @Html.Label("Descripcion")<br />
        @Html.TextBox("Descripcion")
    </p>
    <p>
        <input  type="submit" value="Guardar"/>
    </p>
    <p style="color:darkblue">
        <strong>@ViewBag.mensaje</strong>

    </p>
}

Views/Obrero/Nuevo.cshtml
@model waSEMANA077.Models.Obrero

@{
    ViewBag.Title = "Nuevo";
}

<h2>Nuevo</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Obrero</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_obrero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_obrero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_obrero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dni, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dni, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dni, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.genero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.genero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sueldo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sueldo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sueldo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_naci, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_naci, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_naci, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>